services:
  service:
    build:
      context: ../..
    container_name: cdp-node-backend-template
    networks:
      - cdp-network
    ports:
      - "8085:8085"
    environment:
      PORT: 8085
    healthcheck:
      test: curl http://localhost:8085/health
      start_period: 1s
      interval: 2s

networks:
  cdp-network:
    driver: bridge
